[ClassVersion("1.0.0.0"), FriendlyName("xClusterQuorum")]
class MSFT_xClusterQuorum : OMI_BaseResource
{
    [Key, ValueMap{"Yes"}, Values{"Yes"}] string IsSingleInstance;

    [Write, ValueMap{"NodeMajority", "NodeAndDiskMajority", "NodeAndFileShareMajority", "DiskOnly", "Cloud Witness"}, Values{"NodeMajority", "NodeAndDiskMajority", "NodeAndFileShareMajority", "DiskOnly", "Cloud Witness"}] string Type;

    [Write] String Resource;
	
	[Write] String StorageAccountName;
	
	[Write] String StorageAccountAccessKey;
};
